import './globals.css';
import type { Metadata } from 'next';
import { ThemeModeScript } from 'flowbite-react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className="">{children}</body>
    </html>
  );
}
